# Generated by Django 5.2.7 on 2025-10-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0006_recommendation_book_recommendation_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
